#pragma once

typedef enum
{
    REGISTER_REQUEST = 100,
    LOGIN_REQUEST,
    LIST_USER_FILES_REQUEST,
    UPLOAD_FILE_REQUEST,
    DOWNLOAD_FILE_REQUEST
} requests_e;

typedef enum
{
    REGISTER_RESPONSE = 200,
    LOGIN_RESPONSE,
    LIST_USER_FILES_RESPONSE,
    UPLOAD_FILE_RESPONSE,
    DOWNLOAD_FILE_RESPONSE,
    SERVER_FULL_RESPONSE
} responses_e;